`ANÁLISIS EXPLORATORIO DE DATOS (EDA) Y CARGA DE TRANSFORMACIÓN DE EXTRACCIÓN (ETL)`
____________________________________________________________________________________

`Este archivo de Jupyter Notebooks muestra todos los pasos y procesos utilizados para la realización de la etapa EDA y ETL, incluyendo las funciones que van a ser consumidas por API.`
__________________________________________________________________________________________________________________

Importar bibliotecas necesarias

In [1]:
# Pandas
import pandas as pd
#Numpy
import numpy as np

Creaciones de DataFrame basadas en conjuntos de datos proporcionados en archivos en formatos de texto separados por coma.

In [2]:
amazon_titles = pd.read_csv(r"C:/Users/rocio/OneDrive/Escritorio/henry/PI1/amazon_prime_titles.csv")

In [3]:
disney_titles = pd.read_csv(r"C:/Users/rocio/OneDrive/Escritorio/henry/PI1/disney_plus_titles.csv")

In [4]:
hulu_titles = pd.read_csv(r'C:/Users/rocio/OneDrive/Escritorio/henry/PI1/hulu_titles.csv')

In [5]:
netflix_titles= pd.read_csv(r"C:/Users/rocio/OneDrive/Escritorio/henry/PI1/netflix_titles.csv")

`Análisis exploratorio de datos`

In [6]:
# AMAZON
amazon_titles.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."

In [7]:
#info
amazon_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7586 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [8]:
# Comprobar si el archivo tiene valores nulos
amazon_titles.isnull().sum()

show_id            0
type               0
title              0
director        2082
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [9]:
#DISNEY
disney_titles.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"

In [10]:
#Info
disney_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1450 non-null   object
 1   type          1450 non-null   object
 2   title         1450 non-null   object
 3   director      977 non-null    object
 4   cast          1260 non-null   object
 5   country       1231 non-null   object
 6   date_added    1447 non-null   object
 7   release_year  1450 non-null   int64
 8   rating        1447 non-null   object
 9   duration      1450 non-null   object
 10  listed_in     1450 non-null   object
 11  description   1450 non-null   object
dtypes: int64(1), object(11)
memory usage: 136.1+ KB

In [11]:
# Se comprueba si el archivo tiene valores nulos
disney_titles.isnull().sum()

show_id           0
type              0
title             0
director        473
cast            190
country         219
date_added        3
release_year      0
rating            3
duration          0
listed_in         0
description       0
dtype: int64

In [12]:
#HULU
hulu_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       3073 non-null   object
 1   type          3073 non-null   object
 2   title         3073 non-null   object
 3   director      3 non-null      object
 4   cast          0 non-null      float64
 5   country       1620 non-null   object
 6   date_added    3045 non-null   object
 7   release_year  3073 non-null   int64
 8   rating        2553 non-null   object
 9   duration      2594 non-null   object
 10  listed_in     3073 non-null   object
 11  description   3069 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 288.2+ KB

In [13]:
#Info
hulu_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       3073 non-null   object
 1   type          3073 non-null   object
 2   title         3073 non-null   object
 3   director      3 non-null      object
 4   cast          0 non-null      float64
 5   country       1620 non-null   object
 6   date_added    3045 non-null   object
 7   release_year  3073 non-null   int64
 8   rating        2553 non-null   object
 9   duration      2594 non-null   object
 10  listed_in     3073 non-null   object
 11  description   3069 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 288.2+ KB

In [14]:
# Se comprueba si el archivo tiene valores nulos
hulu_titles.isnull().sum()

show_id            0
type               0
title              0
director        3070
cast            3073
country         1453
date_added        28
release_year       0
rating           520
duration         479
listed_in          0
description        4
dtype: int64

In [15]:
#NETLIX
netflix_titles.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."

In [16]:
#Info
netflix_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [17]:
# Se comprueba si el archivo tiene valores nulos
netflix_titles.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

En conclusión, hay valores nulos considerables que se pueden corregir, pero en general se puede decir que hay buenas condiciones para continuar con el proceso de ETL.

`Extraer, Transformar y Cargar`

Como primer paso, se creará una copia del DF como buena práctica de ETL.

In [18]:
#Amazon
amazon_titles_copy =amazon_titles.copy()
#Disney
disney_titles_copy=disney_titles.copy()
#Hulu
hulu_titles_copy=hulu_titles.copy()
#Netflix
netflix_titles_copy= netflix_titles.copy()

In [19]:
#Agregar una nueva columna para cada conjunto de datos para obtener la plataforma
amazon_titles_copy['Platform'] = 'Amazon'
disney_titles_copy['Platform'] = 'Disney'
hulu_titles_copy['Platform'] = 'Hulu'
netflix_titles_copy['Platform'] = 'Netflix'

In [20]:
#Reemplazando valores nulos
hulu_titles_copy['duration'].fillna('No data',inplace=True)
netflix_titles_copy['duration'].fillna('No data',inplace=True)

En la columna duración tiene la información en forma de números y la unidad de tiempo.
Se creará una función para dividir esta información en dos columnas:

In [21]:
def separa_columna_duration(DF):
    """
     Esta función toma un DataFrame de pandas como argumento y crea dos nuevas columnas, una para la temporada y otra para la duración.
    
    Parametros:
    df(pd.DataFrame): The input DataFrame.
    
    Return:
    None
    
    """
    DF['seasons']=DF["duration"].apply(lambda i: i.split()[0] if i.split()[1]=='Seasons' else '0')
    DF['movie_duration']= DF['duration'].apply(lambda i: i.split()[0] if i.split(" ",1)[1]=='min' or i.split(" ",1)[1]=='mim'  else '0')
    return DF

In [22]:
amazon_titles_copy =separa_columna_duration(amazon_titles_copy)
disney_titles_copy = separa_columna_duration(disney_titles_copy)
hulu_titles_copy = separa_columna_duration(hulu_titles_copy)
tetflix_titles_copy = separa_columna_duration(netflix_titles_copy)

In [23]:
# Eliminación de la duración de la columna original
amazon_titles_copy.drop(columns='duration',inplace=True)
disney_titles_copy.drop(columns='duration',inplace= True)
hulu_titles_copy.drop(columns= 'duration', inplace=True)
netflix_titles_copy.drop(columns='duration',inplace=True)

In [24]:
#Controlo
amazon_titles_copy.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,Platform,seasons,movie_duration
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,"Comedy, Drama",A small fishing village must procure a local d...,Amazon,0,113
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon,0,110
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon,0,74
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon,0,69
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon,0,45

In [25]:
disney_titles_copy.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,Platform,seasons,movie_duration
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,"Animation, Family",Join Mickey and the gang as they duck the halls!,Disney,0,23
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,Comedy,Santa Claus passes his magic bag to a new St. ...,Disney,0,91
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.,Disney,0,23
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,Musical,"This is real life, not just fantasy!",Disney,0,41
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...,Disney,0,0

In [26]:
#Se combinan los DataFrames en uno solo para poder importarlo en la API cuando lo necesite
movies_and_series=pd.concat([amazon_titles_copy, disney_titles_copy, hulu_titles_copy, netflix_titles_copy],axis=0)

In [27]:
#Controlo
movies_and_series.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,Platform,seasons,movie_duration
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,"Comedy, Drama",A small fishing village must procure a local d...,Amazon,0,113
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon,0,110
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon,0,74
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon,0,69

In [28]:
movies_and_series.tail(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,Platform,seasons,movie_duration
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Netflix,2,0
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netflix,0,88
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netflix,0,88
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netflix,0,111

In [29]:
#Se convierten columnas a mayúsculas
movies_and_series.columns = movies_and_series.columns.str.upper()

In [30]:
#Controlo
movies_and_series.head(4)

,SHOW_ID,TYPE,TITLE,DIRECTOR,CAST,COUNTRY,DATE_ADDED,RELEASE_YEAR,RATING,LISTED_IN,DESCRIPTION,PLATFORM,SEASONS,MOVIE_DURATION
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,"Comedy, Drama",A small fishing village must procure a local d...,Amazon,0,113
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon,0,110
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon,0,74
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon,0,69

`Se empieza a trabajar con el nuevo DF`

In [31]:
#Información del nuevo DF
movies_and_series.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22998 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SHOW_ID         22998 non-null  object
 1   TYPE            22998 non-null  object
 2   TITLE           22998 non-null  object
 3   DIRECTOR        14739 non-null  object
 4   CAST            17677 non-null  object
 5   COUNTRY         11499 non-null  object
 6   DATE_ADDED      13444 non-null  object
 7   RELEASE_YEAR    22998 non-null  int64
 8   RATING          22134 non-null  object
 9   LISTED_IN       22998 non-null  object
 10  DESCRIPTION     22994 non-null  object
 11  PLATFORM        22998 non-null  object
 12  SEASONS         22998 non-null  object
 13  MOVIE_DURATION  22998 non-null  object
dtypes: int64(1), object(13)
memory usage: 2.6+ MB

In [32]:
#Transformación tipo fecha
movies_and_series.SEASONS=movies_and_series.SEASONS.astype(int)

In [33]:
#Transformación el tipo de dato de duración
movies_and_series.MOVIE_DURATION= movies_and_series.MOVIE_DURATION.astype(int)

In [34]:
#Exportación a un nuevo DF
movies_and_series.to_csv(r"C:/Users/rocio/OneDrive/Escritorio/henry/PI1/movies_and_series.csv", index=False, header=True)

PermissionError: [Errno 13] Permission denied: 'C:/Users/rocio/OneDrive/Escritorio/henry/PI1/movies_and_series.csv'

`A continuación, se procede a realizar las funciones para hacer las consultas a través de la API posteriormete.`

-----------------------------------------------------------------------------
|                           CONSULTAS A REALIZAR                            |
-----------------------------------------------------------------------------

- 1) Película con mayor duración con filtros opcionales de AÑO, PLATAFORMA Y TIPO DE DURACIÓN. (la función debe llamarse get_max_duration(year, platform, duration_type))

- 2) Cantidad de películas por plataforma con filtro de PLATAFORMA. (La función debe llamarse get_count_platform(platform))
                                           
- 3) Cantidad de películas por plataforma con un puntaje mayor a XX en determinado año (la función debe llamarse get_score_count(platform, scored, year))

(cambiar órden 2x3)

- 4) Actor que más se repite según plataforma y año. (La función debe llamarse get_actor(platform, year))

In [37]:
#1)Esta función consigue la mayor duración según el tipo de película (película/serie), por plataforma y por año. En este ejemplo usaremos 2018 y Hulu"

def get_max_duration(year:int,platform:str,min_or_seasson:str):
    df=movies_and_series[(movies_and_series['RELEASE_YEAR']==year) & (movies_and_series['PLATFORM']==platform)] #segun el año, plataforma y tipo de duracion
    if min_or_seasson == 'min':
        a=df.MOVIE_DURATION.max()
        title=df[df.MOVIE_DURATION==a] ['TITLE'] 
        title=title.to_list()
        title=title[0]
    else:
        a=df.SEASONS.max()
        title=df[df.SEASONS==a] ['TITLE']
        title=title.to_list()
        title=title[0]
    return title

In [38]:
get_max_duration(2018,'Hulu','min')

'The House That Jack Built'

In [ ]:
#opcion b terminar

In [ ]:
def get_max_duration(movies, year=None, platform=None, duration_type=None):
    max_duration = 0
    max_duration_movie = None
    
    for movie in movies:
        if year and movie["year"] != year:
            continue
        if platform and movie["platform"] != platform:
            continue
        if duration_type and movie["duration_type"] != duration_type:
            continue
        
        if movie["duration"] > max_duration:
            max_duration = movie["duration"]
            max_duration_movie = movie
    
    return max_duration_movie

In [39]:
#2) Esta función obtiene el conteo de películas y series (separadas) por plataforma. 
def get_count_plataform(platform:str):
    platform = platform.replace("'","")
    platform = platform.capitalize()
    Count_platform = movies_and_series[(movies_and_series.PLATFORM == platform)]  # Aplicamos una máscara de acuerdo al parámetro
    movies = int(Count_platform[Count_platform.TYPE == 'Movie'].TYPE.value_counts()[0]) # Contamos la cantidad de ocurrencias
    series = int(Count_platform[Count_platform.TYPE == 'TV Show'].TYPE.value_counts()[0])
    # Retornamos el valor en formato str para poder aclarar a qué corresponde cada cantidad
    return platform, f'Movie: {movies}', f'TV Show: {series}'

In [40]:
get_count_plataform("Netflix")

('Netflix', 'Movie: 6131', 'TV Show: 2676')

In [ ]:
#3)Cantidad de películas por plataforma con un puntaje mayor a XX en determinado año (la función debe llamarse get_score_count(platform, scored, year))

terminar

In [ ]:
def get_score_count(df, platform, score, year=None):
    if year is not None:
        df = df[df['RELEASE_YEAR'] == year]
    df = df[df['PLATFORM'] == platform]
    df = df[df['SCORE'] > score]
    return len(df)

In [41]:
#4)Esta función obtiene al actor que más se repite según plataforma y año.
def get_actor(platform:str,year:int):
    platform = platform.replace("'","")
    platform = platform.capitalize()
    actores, repeticiones = list(), list()  # Creamos dos listas vacías para colocar cada actor y la cantidad de veces
    # Aplicamos máscara para obtener una lista de listas de actores, que no tengan nulos
    Cast_list = list(movies_and_series[(movies_and_series.PLATFORM == platform) & (movies_and_series.RELEASE_YEAR == year)].CAST.fillna(''))

    for each in Cast_list:  # Iteramos cada elemento, que es a su vez una lista de actores
        if not(each == '' or each is None):    # Validamos que tenga datos
            list1 = each.split(",") # Separamos por comas, para obtener una lista nueva cuyos elementos sean los actores
            for elem in list1:  # Iteramos sobre esta nueva lista de actores
                elem = elem.strip() # Limpiamos los espacios vacíos
                # Si el actor ya se encuentra en 'actores', entonces sumará 1 en 'apariciones' con el mismo índice
                if elem in actores: 
                    repeticiones[actores.index(elem)] += 1
                # De lo contrario, agregará el actor en 'actores' y 1 en 'apariciones'
                else:    
                    actores.append(elem)
                    repeticiones.append(1)
    if actores == []: return 'No hay datos' # Para el caso de que ambas listas queden vacías, que no retorne error
    # Retornamos la plataforma, el actor que más se repite en esa plataforma y ese año, y cuántas veces lo hace
    return (platform, max(repeticiones), actores[repeticiones.index(max(repeticiones))])

In [42]:
get_actor('Netflix',2018)

('Netflix', 8, 'Andrea Libman')